name: rust-data

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - python=3
  - pip=19.0.3
  - jupyterlab
  - matplotlib>=3.0.0
  - mkl
  - nbsphinx=0.4.2
  - numba>=0.43.1
  - numpydoc
  - pyaml
  - pytest-cov
  - pytest-xdist
  - numpy
  - restructuredtext_lint
  - scipy>=1.2.1
  - Sphinx>=2.0.0
  - black>=20.8b1
  - flake8
  - pytest-flake8
  - pytest
  - sphinx-autobuild
  - tox-conda
  - markupsafe<2.0
  - pip:
      - git+https://github.com/OpenSourceEconomics/respy
      - black-nb
      - flake8-nb
      - apprise
      - pre-commit
      - pysftp
      - pytest-black
      - Py-BOBYQA
      - DFO-LS
      - jupyterlab
      - sphinx-rtd-theme
      - sphinxcontrib-bibtex==1.0
      - sphinxcontrib-svg2pdfconverter[CairoSVG]
